//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.wsTotalExpress {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="webservice_calculo_frete.totalPortType", Namespace="http://edi.totalexpress.com.br/soap/webservice_calculo_frete.total", ConfigurationName="wsTotalExpress.webservice_calculo_fretetotalPortType")]
    public interface webservice_calculo_fretetotalPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calcularFrete) of message calcularFreteRequest does not match the default value (http://edi.totalexpress.com.br/soap/webservice_calculo_frete.total)
        [System.ServiceModel.OperationContractAttribute(Action="urn:simulaFrete#calcularFrete", ReplyAction="*")]
        //[System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Document, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Literal)]
        WindowsFormsApp2.wsTotalExpress.calcularFreteResponse1 calcularFrete(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:simulaFrete#calcularFrete", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsTotalExpress.calcularFreteResponse1> calcularFreteAsync(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://edi.totalexpress.com.br/soap/webservice_calculo_frete.total")]
    public partial class calcularFreteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoServicoField;
        
        private string cepDestinoField;
        
        private string pesoField;
        
        private string valorDeclaradoField;
        
        private string tipoEntregaField;
        
        private bool servicoCODField;
        
        private bool servicoCODFieldSpecified;
        
        private string alturaField;
        
        private string larguraField;
        
        private string profundidadeField;
        
        /// <remarks/>
        public string TipoServico {
            get {
                return this.tipoServicoField;
            }
            set {
                this.tipoServicoField = value;
                this.RaisePropertyChanged("TipoServico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="nonNegativeInteger")]
        public string CepDestino {
            get {
                return this.cepDestinoField;
            }
            set {
                this.cepDestinoField = value;
                this.RaisePropertyChanged("CepDestino");
            }
        }
        
        /// <remarks/>
        public string Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("Peso");
            }
        }
        
        /// <remarks/>
        public string ValorDeclarado {
            get {
                return this.valorDeclaradoField;
            }
            set {
                this.valorDeclaradoField = value;
                this.RaisePropertyChanged("ValorDeclarado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="nonNegativeInteger")]
        public string TipoEntrega {
            get {
                return this.tipoEntregaField;
            }
            set {
                this.tipoEntregaField = value;
                this.RaisePropertyChanged("TipoEntrega");
            }
        }
        
        /// <remarks/>
        public bool ServicoCOD {
            get {
                return this.servicoCODField;
            }
            set {
                this.servicoCODField = value;
                this.RaisePropertyChanged("ServicoCOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ServicoCODSpecified {
            get {
                return this.servicoCODFieldSpecified;
            }
            set {
                this.servicoCODFieldSpecified = value;
                this.RaisePropertyChanged("ServicoCODSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="nonNegativeInteger")]
        public string Altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("Altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="nonNegativeInteger")]
        public string Largura {
            get {
                return this.larguraField;
            }
            set {
                this.larguraField = value;
                this.RaisePropertyChanged("Largura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="nonNegativeInteger")]
        public string Profundidade {
            get {
                return this.profundidadeField;
            }
            set {
                this.profundidadeField = value;
                this.RaisePropertyChanged("Profundidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://edi.totalexpress.com.br/soap/webservice_calculo_frete.total")]
    public partial class DadosFrete : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prazoField;
        
        private string valorServicoField;
        
        /// <remarks/>
        public string Prazo {
            get {
                return this.prazoField;
            }
            set {
                this.prazoField = value;
                this.RaisePropertyChanged("Prazo");
            }
        }
        
        /// <remarks/>
        public string ValorServico {
            get {
                return this.valorServicoField;
            }
            set {
                this.valorServicoField = value;
                this.RaisePropertyChanged("ValorServico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://edi.totalexpress.com.br/soap/webservice_calculo_frete.total")]
    public partial class calcularFreteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoProcField;
        
        private DadosFrete dadosFreteField;
        
        private string erroConsultaFreteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="nonNegativeInteger")]
        public string CodigoProc {
            get {
                return this.codigoProcField;
            }
            set {
                this.codigoProcField = value;
                this.RaisePropertyChanged("CodigoProc");
            }
        }
        
        /// <remarks/>
        public DadosFrete DadosFrete {
            get {
                return this.dadosFreteField;
            }
            set {
                this.dadosFreteField = value;
                this.RaisePropertyChanged("DadosFrete");
            }
        }
        
        /// <remarks/>
        public string ErroConsultaFrete {
            get {
                return this.erroConsultaFreteField;
            }
            set {
                this.erroConsultaFreteField = value;
                this.RaisePropertyChanged("ErroConsultaFrete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularFrete", WrapperNamespace="urn:calcularFrete", IsWrapped=true)]
    public partial class calcularFreteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WindowsFormsApp2.wsTotalExpress.calcularFreteRequest calcularFreteRequest;
        
        public calcularFreteRequest1() {
        }
        
        public calcularFreteRequest1(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest calcularFreteRequest) {
            this.calcularFreteRequest = calcularFreteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularFreteResponse", WrapperNamespace="urn:calcularFrete", IsWrapped=true)]
    public partial class calcularFreteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WindowsFormsApp2.wsTotalExpress.calcularFreteResponse calcularFreteResponse;
        
        public calcularFreteResponse1() {
        }
        
        public calcularFreteResponse1(WindowsFormsApp2.wsTotalExpress.calcularFreteResponse calcularFreteResponse) {
            this.calcularFreteResponse = calcularFreteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webservice_calculo_fretetotalPortTypeChannel : WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webservice_calculo_fretetotalPortTypeClient : System.ServiceModel.ClientBase<WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType>, WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType {
        
        public webservice_calculo_fretetotalPortTypeClient() {
        }
        
        public webservice_calculo_fretetotalPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webservice_calculo_fretetotalPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webservice_calculo_fretetotalPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webservice_calculo_fretetotalPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.wsTotalExpress.calcularFreteResponse1 WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType.calcularFrete(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1 request) {
            return base.Channel.calcularFrete(request);
        }
        
        public WindowsFormsApp2.wsTotalExpress.calcularFreteResponse calcularFrete(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest calcularFreteRequest) {
            WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1 inValue = new WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1();
            inValue.calcularFreteRequest = calcularFreteRequest;
            WindowsFormsApp2.wsTotalExpress.calcularFreteResponse1 retVal = ((WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType)(this)).calcularFrete(inValue);
            return retVal.calcularFreteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.wsTotalExpress.calcularFreteResponse1> WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType.calcularFreteAsync(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1 request) {
            return base.Channel.calcularFreteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.wsTotalExpress.calcularFreteResponse1> calcularFreteAsync(WindowsFormsApp2.wsTotalExpress.calcularFreteRequest calcularFreteRequest) {
            WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1 inValue = new WindowsFormsApp2.wsTotalExpress.calcularFreteRequest1();
            inValue.calcularFreteRequest = calcularFreteRequest;
            return ((WindowsFormsApp2.wsTotalExpress.webservice_calculo_fretetotalPortType)(this)).calcularFreteAsync(inValue);
        }
    }
}
